name: crosscrop-pure
version: 0.1.0.0
github: "KornSiwat/crosscrop-pure"
license: BSD3
author: "Siwat Ponpued"
maintainer: "siwatponpued@gmail.com"
copyright: "2021 Siwat Ponpued"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/KornSiwat/crosscrop-pure#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - time
  - composition-extra
  - lens

library:
  source-dirs: src

executables:
  crosscrop-pure-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - crosscrop-pure
    when:
      - condition: false
        other-modules: Paths_crosscrop_pure

tests:
  crosscrop-pure-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - crosscrop-pure
